export class LayerManager{
  constructor(editor){this.e=editor;this.items=[];this.selected=0}
  reset(){this.items=[];this.add("Background");this.selected=0}
  make(name,type="layer"){if(type==="group")return {id:crypto.randomUUID(),name,type,visible:true,locked:false,opacity:1,children:[]};const c=document.createElement("canvas");c.width=this.e.width*(devicePixelRatio||1);c.height=this.e.height*(devicePixelRatio||1);c.style.width=this.e.width+"px";c.style.height=this.e.height+"px";const x=c.getContext("2d");x.setTransform(devicePixelRatio||1,0,0,devicePixelRatio||1,0,0);return {id:crypto.randomUUID(),name,type,visible:true,locked:false,opacity:1,blend:"source-over",canvas:c}}
  add(name="Layer"){const l=this.make(name);this.items.push(l);this.selected=this.items.length-1;this.ui();return l}
  addGroup(name="Group"){const g=this.make(name,"group");this.items.push(g);this.selected=this.items.length-1;this.ui();return g}
  active(){return this.items[this.selected]}
  select(i){if(i>=0&&i<this.items.length)this.selected=i;this.ui();this.e.render()}
  remove(){if(this.items.length<=1)return;this.items.splice(this.selected,1);this.selected=Math.max(0,this.selected-1);this.ui();this.e.render();this.e.snapshot("Delete Layer")}
  duplicate(){const l=this.active();if(!l||l.type!=="layer")return;const n=this.make(l.name+" copy");n.opacity=l.opacity;n.blend=l.blend;n.visible=l.visible;n.canvas.getContext("2d").drawImage(l.canvas,0,0);this.items.splice(this.selected+1,0,n);this.selected++;this.ui();this.e.render();this.e.snapshot("Duplicate Layer")}
  move(d){const i=this.selected,j=i+d;if(j<0||j>=this.items.length)return;[this.items[i],this.items[j]]=[this.items[j],this.items[i]];this.selected=j;this.ui();this.e.render();this.e.snapshot("Move Layer")}
  composite(ctx){for(const l of this.items){if(!l.visible||l.type!=="layer")continue;ctx.save();ctx.globalAlpha=l.opacity;ctx.globalCompositeOperation=l.blend;ctx.drawImage(l.canvas,0,0,this.e.width,this.e.height);ctx.restore()}}
  serialize(){return this.items.map(l=>{if(l.type==="group")return {...l,children:[]};return {id:l.id,name:l.name,type:l.type,visible:l.visible,locked:l.locked,opacity:l.opacity,blend:l.blend,data:l.canvas.toDataURL("image/png")}})}
  async restore(arr){this.items=[];for(const d of arr){if(d.type==="group"){this.items.push({...d,children:[]});continue}const l=this.make(d.name);l.id=d.id;l.visible=d.visible;l.locked=d.locked;l.opacity=d.opacity;l.blend=d.blend;const img=new Image();await new Promise(res=>{img.onload=()=>{l.canvas.getContext("2d").drawImage(img,0,0,this.e.width,this.e.height);res()};img.src=d.data});this.items.push(l)}if(!this.items.length)this.add();this.selected=0;this.ui()}
  ui(){const box=document.querySelector("#layers");box.innerHTML="";this.items.slice().reverse().forEach((l,rev)=>{const i=this.items.length-1-rev,row=document.createElement("div");row.className="layer-row"+(i===this.selected?" selected":"");const eye=document.createElement("button");eye.className="eye";eye.textContent=l.visible?"◉":"○";eye.onclick=e=>{e.stopPropagation();l.visible=!l.visible;this.ui();this.e.render()};const lock=document.createElement("button");lock.className="lock";lock.textContent=l.locked?"🔒":"";lock.onclick=e=>{e.stopPropagation();l.locked=!l.locked;this.ui()};const th=document.createElement("canvas");th.className="layer-thumb";th.width=72;th.height=64;if(l.type==="layer")th.getContext("2d").drawImage(l.canvas,0,0,72,64);const name=document.createElement("span");name.className="layer-name";name.textContent=l.name;name.ondblclick=()=>{const n=prompt("Layer name",l.name);if(n){l.name=n;this.ui();this.e.snapshot("Rename Layer")}};row.append(eye,lock,th,name);row.onclick=()=>this.select(i);box.append(row)})}
}
